### ISSUE TITLE
Calculate b0 (recall that Y intercept = B0 +B1 Intercept   ) 

### ISSUE THREAD

**Issue by kidistbetter105** [DS4PS/cpp-523-sum-2021#1]
Calculate b0 (recall that Y intercept = B0 +B1 Intercept   )

**Comment by kidistbetter105** [comment]
cpp- 523

This is the question from the assignment(Lab1) question number 3

**Comment by lecy** [comment]
y-bar = b0 + (b1)(x-bar)

y-bar is the mean of Y and x-bar is the mean of X

solve for b0

**Comment by kidistbetter105** [comment]
Thank you very much !

**Comment by kidistbetter105** [comment]
Thank you it helps me a lot!
