### ISSUE TITLE
Hello David!  I was doing the assessment and it just submites itself before I even read  the whole questions. What do I have to do ?  regards!

### ISSUE THREAD

**Issue by kidistbetter105** [DS4PS/cpp-523-sum-2021#2]

**Comment by Schlinkert** [comment]
Yes, that was resolved. Sorry about the notifications, I am watching now. I could’ve sworn I did that at the beginning of class.

**Comment by lecy** [comment]
Ok, great. Am closing this out since it wouldn't be relevant to other students.
